# Generated by Django 3.2.6 on 2021-10-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=1)),
                ('p2', models.CharField(max_length=1)),
                ('p3', models.CharField(max_length=1)),
                ('p4', models.CharField(max_length=1)),
                ('p5', models.CharField(max_length=1)),
                ('p6', models.CharField(max_length=1)),
                ('p7', models.CharField(max_length=1)),
                ('p8', models.CharField(max_length=1)),
                ('p9', models.CharField(max_length=1)),
                ('p10', models.CharField(max_length=1)),
                ('ob1', models.CharField(max_length=50)),
                ('ob2', models.CharField(max_length=50)),
                ('answered_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
