# Generated by Django 3.2.6 on 2021-10-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_medical',
            new_name='is_answered',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_physiotherapist',
        ),
    ]
